Module6 task1
htmlacademy-php/138767-yeticave-12 pull request #10
Opened 2021-02-10 20:43 UTC by Lavrik15

2021-02-11 08:05 UTC, mihan007 requested changes
Привет, Андрей! Приятно было изучить твой PR, хорошо поработал. Я предложил ряд доработок, которые, по-моему мнению, позволят улучшить этот код. Рассмотри, пожалуйста.

2021-02-11 08:05 UTC, mihan007 commented on 404.php
> +                <li class="nav__item">
Список категорий у тебя лежит в базе. Их ровно как и на другие страницы надо сюда передавать и отображать

2021-02-11 08:05 UTC, mihan007 commented on 404.php
> +            <li class="nav__item">
И тут список категорий из базы

2021-02-11 08:05 UTC, mihan007 commented on init.php
> +    $categories_sql = "SELECT category_id, name, symbol_code FROM categories;";
рекомендую для упорядочения порядка категорий отсортировать их. например, отсортировать по имени в алфавитном порядке. или даже посложнее - по количеству лотов в категории по убыванию. 

это рекомендация, не более. цель - сейчас база будет рандомно возвращать список категорий, как ей удобно. и есть вероятность, что пользователь зайдя несколько раз увидит нужную ему категорию то в начале, то в середине, то в конце списка. при этом он не будет понимать логики нахождения этой категории. в общем, ему будет некомфортно. а нам надо, чтобы ему было хорошо))

2021-02-11 08:05 UTC, mihan007 commented on lot.php
> +        $page_content = include_template("404.php");
в этот шаблон передашь список категорий

2021-02-11 08:05 UTC, mihan007 commented on templates/layout.php
> +                    <a href="pages/all-lots.html"><?= htmlspecialchars($category["name"]) ?></a>
не уверен в корректности ссылки. ты показываешь имя категории, а ссылка ведет на все лоты. скорее всего ссылка должна содержать get параметром с id категории. если на текущем этапе выполнения ТЗ это не нужно, то пропускай, сделаем позже

2021-02-11 08:05 UTC, mihan007 commented on templates/lot.php
> +<!--            <div class="history">-->
если подходить к этому PR как к реальному из моей практики, то
1. я не пропускаю обычно никогда "мертвый" код. у нас есть система контроля версий и место мертвого кода в ней
2. в данном случае я понимаю для чего ты его оставил. можем поступить так
- либо написать сверху закомментированной части почему она тут. что-то вроде "тут будет список ставок, сделаю позже"
- либо же вывести этот блок с парой строк. и в этих строках написать вместо реальных данных то, что будет в этом месте. "имя пользователя", "его ставка в рублях", "относительное время ставки". я за этот вариант.

2021-02-11 08:05 UTC, mihan007 commented on templates/main.php
> +                        <a class="text-link" href="../lot.php?<?= "category=" . $item["lot_category_id"] . "&lot=" . $item["lot_id"] ?>">
- посмотри, пожалуйста, на https://www.php.net/manual/ru/function.http-build-query.php. она значительно упрощает процесс создания url.
- я бы вообще формирование ссылок раскидал по функциям. эти функции сложил бы в файл routes.php и использовал уже по коду. например, в этом случае было бы что-то вроде
```
<a class="text-link" href="<?= get_lot_page_url($item) ?>">
```

2021-03-07 11:31 UTC, Lavrik15 commented on templates/lot.php
> +<!--            <div class="history">-->
Пока что просто обозначил в коментах, что это за закоментированый код

2021-03-07 11:32 UTC, Lavrik15 commented on templates/layout.php
> +                    <a href="pages/all-lots.html"><?= htmlspecialchars($category["name"]) ?></a>
Не нашел в ТЗ, поэтому решил оставить

2021-03-07 11:33 UTC, Lavrik15 commented on lot.php
> +        $page_content = include_template("404.php");
этот файл я совсем удалил) и сделал шаблон, который вкладывается в основной шаблон. В основном шаблоне уже есть категории

2021-03-07 20:07 UTC, mihan007 approved these changes

2021-03-07 20:07 UTC, mihan007 commented on init.php
> +    if ($lot_id) {
тут лучше уменьшить сложность функции и сразу выдавать false.
```
if (!$lot_id) {
  return false;
}
```

2021-03-07 20:08 UTC, mihan007 commented
@Lavrik15 принял. обрати внимание на
![image](https://user-images.githubusercontent.com/939122/110253196-0164b380-7f9a-11eb-8346-9dd9a6536efc.png)
пригодится дальше

2021-03-07 20:08 UTC, merged