Работаем с датой
htmlacademy-php/138767-yeticave-12 pull request #6
Opened 2020-08-23 16:30 UTC by Lavrik15

---
:mortar_board: [Работаем с датой](https://up.htmlacademy.ru/php/12/user/138767/tasks/8)

2020-08-24 05:27 UTC, Sergey-Rozhkov commented on helpers.php
> +        print($name);
Это точно тут должно быть ?

2020-08-24 05:28 UTC, Sergey-Rozhkov commented on helpers.php
>      if ($price_value >= 1000) {
по сути это `else`

2020-11-25 15:01 UTC, mihan007 requested changes

2020-11-25 15:01 UTC, mihan007 commented on templates/main.php
> +                        <div class="lot__timer timer <?= get_date_range($item["date"])[0] == 0 ? "timer--finishing" : ""; ?> ">
1. Функцию get_date_range лучше вызвать один раз и сохранить ее ответ переменной, чтобы не дергать ее каждый раз. Функция может быть сложной и каждый вызов замедлит страницу
2. А что будет с left_time_hours, когда мы передадим туда прошедшую дату? Как этот случай обработаем?

2020-12-03 18:57 UTC, Lavrik15 commented on templates/main.php
> +                        <div class="lot__timer timer <?= get_date_range($item["date"])[0] == 0 ? "timer--finishing" : ""; ?> ">
1. Поправил
2. Если дата прошедшая, то блок со временим будет скрыт

2020-12-07 11:12 UTC, mihan007 commented on templates/main.php
> +                $date_range = get_date_range($item["date"]);
тут можно [$hours, $minutes] = get_date_range($item["date"]);

2020-12-07 11:12 UTC, mihan007 approved these changes
👍

2020-12-07 11:12 UTC, merged