Module5 task1
htmlacademy-php/138767-yeticave-12 pull request #9
Opened 2021-01-06 10:20 UTC by Lavrik15

2021-01-06 16:24 UTC, mihan007 requested changes
Привет! Хорошо получилось. Полирнем и будет огурчик.

2021-01-06 16:24 UTC, mihan007 commented on index.php
> +if ($link) {
1. вообще неявно откуда у тебя $link взялся. скорее всего он тут и не нужен. ты, когда к базе подключаешься, то сразу проверь его. если не подключился, то сразу падай с ошибкой типа "Не могу подключиться к бд". Дальнейшая работа скрипта без базы смысла не имеет поэтому лучше упасть, это упростит код далее.
2. переменные, которые ты в ```include_template("main.php"``` передаешь надо инициализировать вне вложенных конструкций. сейчас ты их инициализируешь  только в if, так не надо. В if ты можешь их изменить, но существовать они у тебя уже должны.
```
$lots = [];
$categories = [];
```

2021-01-06 16:24 UTC, mihan007 commented on init.php
> +require_once "config/db.php";
правильное решение

2021-01-06 16:24 UTC, mihan007 commented on templates/layout.php
> +                    <a href="pages/all-lots.html<?= $category["category_name"] ?>" ><?= htmlspecialchars($category["name"]) ?></a>
может я чего-то не понимаю, но разве ссылки тут корректными будут?
pages/all-lots.html<?= $category["category_name"] ?> => pages/all-lots.html**category_name**, когда должно быть что-то вроде pages/all-lots.html?category=**category_name**

2021-01-06 16:24 UTC, mihan007 commented on templates/main.php
> +                <a class="promo__link" href="pages/all-lots.html"><?= $category['name'] ?></a>
а тут ссылки корректной совсем нет, нужна

2021-01-06 16:32 UTC, Lavrik15 commented on index.php
> +if ($link) {
@mihan007 По второму пункту. А они уже существуют в файле init.php Наверное их лучше перенести index.php?

2021-01-06 16:35 UTC, Lavrik15 commented on templates/layout.php
> +                    <a href="pages/all-lots.html<?= $category["category_name"] ?>" ><?= htmlspecialchars($category["name"]) ?></a>
@mihan007 не помню зачем я это сюда добавил... в задаче этого не было. удалю пока что

2021-01-06 16:46 UTC, mihan007 commented on index.php
> +if ($link) {
@Lavrik15 да, имеет смысл явно их объявлять там, где они используются. в подключаемые файлы вполне можно размещать функции, которые заполняют эти переменные. но сами они должны быть тут. то есть вполне допустимо такое
```
require_once ("db.php")
$lots = get_lots_from_db();
$categories = get_categories_from_db();
```
а функции get_lots_from_db и get_categories_from_db у тебя уже будут в db.php

это все нужно, чтобы ты сам через какое-то время или разработчик другой не сидел и не копался в коде, не понимая откуда переменная возникла и вообще к чему она. чем ближе переменная объявлена к месту использования - тем лучше.

2021-01-10 23:17 UTC, mihan007 requested changes
часть правок еще не доделана, жду

2021-01-10 23:17 UTC, mihan007 commented on templates/layout.php
> +                    <a href="pages/all-lots.html<?= $category["category_name"] ?>" ><?= htmlspecialchars($category["name"]) ?></a>
@Lavrik15 тут забыл поправить?

2021-01-10 23:17 UTC, mihan007 commented on templates/main.php
> +                <a class="promo__link" href="pages/all-lots.html"><?= $category['name'] ?></a>
@Lavrik15 и тут надо поправить

2021-01-26 06:21 UTC, Lavrik15 commented on templates/layout.php
> +                    <a href="pages/all-lots.html<?= $category["category_name"] ?>" ><?= htmlspecialchars($category["name"]) ?></a>
поправил

2021-01-26 06:22 UTC, Lavrik15 commented on templates/main.php
> +                <a class="promo__link" href="pages/all-lots.html"><?= $category['name'] ?></a>
а тут же все ок? ссылки на категории, если я не ошибаюсь должны быть реализованы в 6 модуле. Здесь пока что добавляется класс для ссылки в меню категорий

2021-01-26 06:25 UTC, mihan007 commented on templates/main.php
> +                <a class="promo__link" href="pages/all-lots.html"><?= $category['name'] ?></a>
ок, тогда сделаем дальше

2021-01-27 18:44 UTC, mihan007 approved these changes

2021-01-27 18:44 UTC, merged